/*
 * YARA Rules: Anthropic Claude API Credentials
 *
 * Author      : yara-apikey-rules contributors
 * Date        : 19-03-2026
 * Version     : 1.0
 * Reference   : https://docs.anthropic.com/en/api/getting-started
 *               https://docs.gitguardian.com/secrets-detection/detectors/specifics/claude_api_key
 *
 * Coverage:
 *   - Claude standard API keys     (sk-ant-api03- prefix)
 *   - Claude OAuth Access Tokens   (sk-ant-oat01- prefix) [Claude Code / Max/Pro subscriptions]
 *   - Claude Admin API keys        (ANTHROPIC_ADMIN_API_KEY / x-api-key header variant)
 *   - Base64 anchor for binary detection (c2stYW50LQ== = "sk-ant-")
 *
 * Key structure:
 *   Standard API key  : sk-ant-api03-[A-Za-z0-9_-]{93}AA
 *                       Total length: ~108 chars
 *                       Always ends with "AA" (documented characteristic)
 *                       Source: Semgrep 2025 research on scanner false negatives
 *
 *   OAuth token       : sk-ant-oat01-[A-Za-z0-9_-]{93}
 *                       Generated by `claude setup-token` for Claude Code / Max/Pro
 *                       Not accepted by third-party integrations expecting api03 format
 *                       Source: anthropics/claude-code issue #18340
 *
 * Environment variable: ANTHROPIC_API_KEY
 * Request header      : x-api-key: <key>
 *
 * False positive note:
 *   The "sk-ant-api03-" prefix is extremely specific. False positives are near zero.
 *   The trailing "AA" is a bonus validator for the standard key format.
 */

rule Anthropic_Claude_API_Key
{
    meta:
        description    = "Detects Anthropic Claude standard API keys (sk-ant-api03- prefix)"
        author         = "yara-apikey-rules"
        date           = "2025-03-03"
        version        = "1.0"
        reference      = "https://docs.anthropic.com/en/api/getting-started"
        confidence     = "HIGH"
        false_positive = "LOW"
        severity       = "CRITICAL"
        tags           = "anthropic,claude,llm,api-key"

    strings:
        // Full pattern — ends with AA (documented stable characteristic, Semgrep 2025)
        $key_full     = /sk-ant-api03-[A-Za-z0-9_\-]{93}AA/

        // Relaxed variant — catches keys where trailing AA is cut off (paste truncation)
        $key_relaxed  = /sk-ant-api03-[A-Za-z0-9_\-]{80,}/

    condition:
        any of them
}


rule Anthropic_Claude_OAuth_Token
{
    meta:
        description    = "Detects Anthropic Claude OAuth Access Tokens (sk-ant-oat01- prefix, used by Claude Code / Max/Pro)"
        author         = "yara-apikey-rules"
        date           = "2025-03-03"
        version        = "1.0"
        reference      = "https://github.com/anthropics/claude-code/issues/18340"
        confidence     = "HIGH"
        false_positive = "LOW"
        severity       = "HIGH"
        tags           = "anthropic,claude,oauth,access-token,claude-code"

    strings:
        // OAuth token generated by `claude setup-token` for Max/Pro subscribers
        $oat_token    = /sk-ant-oat01-[A-Za-z0-9_\-]{80,}/

    condition:
        $oat_token
}


rule Anthropic_API_Key_In_Config
{
    meta:
        description    = "Detects Anthropic API keys in config files, env files, or source code via variable name anchors"
        author         = "yara-apikey-rules"
        date           = "2025-03-03"
        version        = "1.0"
        confidence     = "HIGH"
        false_positive = "LOW"
        severity       = "CRITICAL"
        tags           = "anthropic,claude,api-key,config,env"

    strings:
        // Standard environment variable
        $env1     = /ANTHROPIC_API_KEY\s*=\s*['"]?sk-ant-[A-Za-z0-9_\-]{10,}['"]?/

        // Admin API key (used for organization management endpoints)
        $env2     = /ANTHROPIC_ADMIN(?:[_\.]?API[_\.]?KEY)?\s*=\s*['"]?sk-ant-[A-Za-z0-9_\-]{10,}['"]?/  nocase

        // JSON config (e.g. .claude/settings.json, openclaw.json)
        $json1    = /"ANTHROPIC_API_KEY"\s*:\s*"sk-ant-[A-Za-z0-9_\-]{10,}"/

        // x-api-key header in curl/HTTP config
        $header1  = /x-api-key:\s*sk-ant-[A-Za-z0-9_\-]{10,}/  nocase

        // Python/JS SDK instantiation patterns
        $sdk1     = /api_key\s*=\s*['"]sk-ant-api03-[A-Za-z0-9_\-]{10,}['"]/
        $sdk2     = /apiKey\s*:\s*['"]sk-ant-api03-[A-Za-z0-9_\-]{10,}['"]/

    condition:
        any of them
}


rule Anthropic_API_Key_Base64_Anchor
{
    meta:
        description    = "Detects base64-encoded Anthropic key prefix (c2stYW50LQ== = 'sk-ant-') in binaries or malware"
        author         = "yara-apikey-rules"
        date           = "2025-03-03"
        version        = "1.0"
        reference      = "https://www.sentinelone.com/labs/malicious-actors-use-of-openai-keys/"
        confidence     = "MEDIUM"
        false_positive = "LOW"
        severity       = "HIGH"
        tags           = "anthropic,claude,base64,binary,malware"

    strings:
        // base64("sk-ant-") = "c2stYW50LQ=="
        $b64_prefix   = "c2stYW50LQ=="

        // base64("sk-ant-api") = "c2stYW50LWFwaQ=="
        $b64_prefix2  = "c2stYW50LWFwaQ=="

    condition:
        any of them
}
